bridge1:
	python bridge.py --core=ws://127.0.0.1:8082/ws --edge=ws://127.0.0.1:8081/ws --realm=realm1
#	python bridge.py --core=ws://127.0.0.1:8081/ws --edge=ws://127.0.0.1:8082/ws --realm=realm1
#	python bridge.py --core=ws://127.0.0.1:8083/ws --edge=ws://127.0.0.1:8081/ws --realm=realm1

bridge2:
	python bridge.py --core=ws://127.0.0.1:8083/ws --edge=ws://127.0.0.1:8082/ws --realm=realm1
