test:
	PYTHONPATH=../crossbar python -m crossbar.controller.cli start
	#PYTHONPATH=../crossbar python -m crossbar.controller.cli start --loglevel=verbose --config=config_using_container.json
	#PYTHONPATH=${CROSSBAR_REPOS_ROOT}/crossbar python -m crossbar.controller.cli start --loglevel=verbose
	#PYTHONPATH=${CROSSBAR_REPOS_ROOT}/crossbar python -m crossbar.controller.cli start
