default: test

test_opt:
	NODE_PATH=/home/ubuntu/crossbarexamples/demos/_demo_launcher/web/node_modules \
	/opt/crossbar/bin/crossbar start --config=config_prod.json

test:
	NODE_PATH=/home/ubuntu/crossbarexamples/demos/_demo_launcher/web/node_modules \
        crossbar start --config=config_prod.json

