start:
	PYTHONPATH=../../crossbar python -m crossbar.controller.cli start

check:
	PYTHONPATH=../../crossbar python -m crossbar.controller.cli check

upgrade:
	PYTHONPATH=../../crossbar python -m crossbar.controller.cli upgrade
