client1:
	PYTHONPATH="${CROSSBAR_REPOS_ROOT}/autobahn-python" python client1.py

client2:
	PYTHONPATH="${CROSSBAR_REPOS_ROOT}/autobahn-python" python client2.py

client3:
	PYTHONPATH="${CROSSBAR_REPOS_ROOT}/autobahn-python" python client3.py
