default:
	@echo "Targets:"
	@echo ""
	@echo "   test              Run a TLS router and a TLS client component in a container"

test:
	PYTHONPATH=../../../crossbar python -m crossbar.controller.cli start
