env = Environment()

env.Append(CXXFLAGS=['-std=c++11',
                     '-O2',
                     '-Wall',
                     '-pedantic',
                     '-Wno-deprecated-declarations',
                     '-Wno-unused-local-typedefs',
                     '-Wl,--no-as-needed',
                     '-pthread'])
env.Append(CPPPATH=['/usr/local/include'])

#env.Append(LINKFLAGS=['-pthread', '--static', '-static-libgcc'])
env.Append(LINKFLAGS=['-pthread'])

env.Append(LIBPATH=['/usr/lib'])

env.Append(LIBS=['boost_thread', 'boost_system', 'msgpackc'])

env.Program('client.cpp')
