crossbar:
	PYTHONPATH=../../../../crossbar python -m crossbar.controller.cli start

client:
	python client.py --key client01.key
#	python client.py --realm devices --authid client01@example.com --key client01.key

bad_client:
	python client.py --key client01-bad.key
