test:
	crossbar start --cbdir=./working/.crossbar
	crossbar start --cbdir=./failure1/.crossbar
	crossbar start --cbdir=./failure2/.crossbar
	crossbar start --cbdir=./failure3/.crossbar
	crossbar start --cbdir=./failure4/.crossbar
	crossbar start --cbdir=./failure5/.crossbar
	crossbar start --cbdir=./failure6/.crossbar
	crossbar start --cbdir=./failure7/.crossbar
	crossbar start --cbdir=./failure8/.crossbar
