CROSSBAR=crossbar

status:
	$(CROSSBAR) status

run_config1:
	$(CROSSBAR) start --config=config1.json

run_client_subscribe:
	python client-subscribe.py

run_client_publish:
	python client-publish.py
