crossbar:
	MYSECRET="secret123" crossbar start

crossbar_database:
	MYSECRET="secret123" crossbar start --config=config-database.json

crossbar_rtrpxy_database:
	MYSECRET="secret123" crossbar edge start --config=config-rtrpxy-database.json

client:
	MYSECRET="secret123" python client.py client1
