crossbar:
	PYTHONPATH=../../../../crossbar python -m crossbar.controller.cli start

crossbar_debug:
	PYTHONPATH=../../../../crossbar python -m crossbar.controller.cli start --loglevel=debug

client:
	PYTHONPATH=../../../../autobahn python client.py
