test_all: test_anonymous test_cookie test_cryptosign test_scram test_ticket test_tls test_wampcra

test_anonymous:
	./test_anonymous.sh

test_cookie:
	./test_cookie.sh

test_cryptosign:
	./test_cryptosign.sh

test_scram:
	./test_scram.sh

test_ticket:
	./test_ticket.sh

test_tls:
	./test_tls.sh

test_wampcra:
	./test_wampcra.sh
