client:
	python client.py --realm devices --authid client01@example.com --key client01.key

client_ssh_agent:
	python client_ssh_agent.py --realm devices --authid client02@example.com --clientkey ~/.ssh/id_ed25519.pub
